apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: local
  labels:
    app: mysql-db
    env: project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
      env: project
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-db
        env: project
    spec:
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: "/run/desktop/mnt/host/c/Users/Eugene_Moiseev/mysql-data"
            type: DirectoryOrCreate
      containers:
        - name: mysql
          image: mysql/mysql-server:5.7

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: "3000Mi"
            requests:
              memory: "1000Mi"

---
apiVersion: v1
kind: Service

metadata:
  name: mysql-service
  namespace: local
  labels:
    app: mysql-db
    env: project

spec:
  type: NodePort
  selector:
    app: mysql-db
    env: project
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30000
      name: db

