apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: local
  labels:
    app: pgadmin
    env: petronet

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
      env: petronet
  template:
    metadata:
      name: pgadmin-pod
      labels:
        app: pgadmin
        env: petronet
    spec:
      volumes:
        - name: config
          hostPath:
            path: /d/env/docker/pgadmin
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@email"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: config
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "100Mi"
---
apiVersion: v1
kind: Service

metadata:
  name: pgadmin-service
  namespace: local
  labels:
    app: pgadmin
    env: petronet

spec:
  type: NodePort
  selector:
    app: pgadmin
    env: petronet
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
      name: ui



