apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: local
  labels:
    app: postgres-db
    env: petronet

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
      env: petronet
  template:
    metadata:
      name: postgres-pod
      labels:
        app: postgres-db
        env: petronet
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "300Mi"

---
apiVersion: v1
kind: Service

metadata:
  name: postgres-service
  namespace: local
  labels:
    app: postgres-db
    env: petronet

spec:
  type: NodePort
  selector:
    app: postgres-db
    env: petronet
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30000
      name: db

