apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: local
  labels:
    app: postgres-db
    env: project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
      env: project
  template:
    metadata:
      name: postgres-pod
      labels:
        app: postgres-db
        env: project
    spec:
      volumes:
#        - name: db
#          hostPath:
#            path:  /tmp/postgres-10.2-data
#            type: DirectoryOrCreate
        - name: db
          hostPath:
            path: "/d/env/docker/postgres"
            type: DirectoryOrCreate
      containers:
        - name: postgres
          image: postgres:10.2
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
#            - name: PGDATA
#              value: /postgresql/data
#          volumeMounts:
#            - mountPath: /postgresql/data
#              name: db
          resources:
            limits:
              memory: "3000Mi"
            requests:
              memory: "1000Mi"

---
apiVersion: v1
kind: Service

metadata:
  name: postgres-service
  namespace: local
  labels:
    app: postgres-db
    env: project

spec:
  type: NodePort
  selector:
    app: postgres-db
    env: project
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30000
      name: db

