apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-stomp-deployment
  namespace: local
  labels:
    app: rabbit
    env: apix

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
      env: apix
  template:
    metadata:
      name: rabbitmq-stomp-pod
      labels:
        app: rabbit
        env: apix
    spec:
      containers:
        - name: rabbitmq-stomp
          image: byteflair/rabbitmq-stomp
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "300Mi"

---
apiVersion: v1
kind: Service

metadata:
  name: rabbitmq-stomp-service
  namespace: local
  labels:
    app: rabbit
    env: apix

spec:
  type: NodePort
  selector:
    app: rabbit
    env: apix
  ports:
    - protocol: TCP
      port: 15672
      nodePort: 32673
      name: ui
    - protocol: TCP
      port: 5672
      nodePort: 32672
      name: amqp
    - protocol: TCP
      port: 61613
      nodePort: 32674
      name: stomp


